x-log: &log
  options:
    max-size: '50m'
    max-file: '3'
  driver: json-file

x-base: &base
  restart: always
  stop_grace_period: ${STOP_GRACE_PERIOD-30}s
  logging: *log
  env_file:
    - .env

services:
  db:
    <<: *base
    container_name: db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tourists_production"
    volumes:
      - "/tmp/postgres:/var/lib/postgresql/data/"
      - tmp:/tmp
    ports:
      - 5432:5432
  
  tourists:
    <<: *base
    container_name: tourists
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      RAILS_MASTER_KEY: 3a36020d163a4da6e5f6a2fa56db2238

volumes:
  tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m
